namespace ApiPortal.ModelSoftland
{
    public class Cabecera
    {
        public string tipo { get; set; }
        public int? nroint { get; set; }
        public string subtipodocto { get; set; }
        public string codbode { get; set; }
        public string codcaja { get; set; }
        public int? folio { get; set; }
        public string concepto { get; set; }
        public string estado { get; set; }
        public DateTime? fecha { get; set; }
        public DateTime? fechavenc { get; set; }
        public string glosa { get; set; }
        public int? orden { get; set; }
        public int? factura { get; set; }
        public string auxtipo { get; set; }
        public string codaux { get; set; }
        public string codicc { get; set; }
        public string codbod { get; set; }
        public int? auxguianum { get; set; }
        public string auxguiafec { get; set; }
        public int? auxdocnum { get; set; }
        public string auxdocfec { get; set; }
        public string codlugardesp { get; set; }
        public string codlistaprecio { get; set; }
        public string codreserva { get; set; }
        public string codvendedor { get; set; }
        public string codmoneda { get; set; }
        public int? equivalencia { get; set; }
        public string patente { get; set; }
        public string retiradopor { get; set; }
        public string usuario { get; set; }
        public double? netoafecto { get; set; }
        public double? netoexento { get; set; }
        public double iva { get; set; }
        public double? porcdesc01 { get; set; }
        public double? descto01 { get; set; }
        public double? porcdesc02 { get; set; }
        public double? descto02 { get; set; }
        public double? porcdesc03 { get; set; }
        public double? descto03 { get; set; }
        public double? porcdesc04 { get; set; }
        public double? descto04 { get; set; }
        public double? porcdesc05 { get; set; }
        public double? descto05 { get; set; }
        public double? totaldesc { get; set; }
        public double? flete { get; set; }
        public double? embalaje { get; set; }
        public double? total { get; set; }
        public double? stockactualizado { get; set; }
        public int? enmantencion { get; set; }
        public string cuenta { get; set; }
        public string centrodecosto { get; set; }
        public double? subtotal { get; set; }
        public string condpago { get; set; }
        public string contabventa { get; set; }
        public string contabcosto { get; set; }
        public string contdesppend { get; set; }
        public string contconsumo { get; set; }
        public string contvtacomp { get; set; }
        public string solicitadopor { get; set; }
        public string despachadopor { get; set; }
        public string nomaux { get; set; }
        public string rutaux { get; set; }
        public string comaux { get; set; }
        public string ciuaux { get; set; }
        public string paiaux { get; set; }
        public string diraux { get; set; }
        public string fonaux { get; set; }
        public string faxaux { get; set; }
        public string comdch { get; set; }
        public string ciudch { get; set; }
        public string paidch { get; set; }
        public string atdch { get; set; }
        public string dirdch { get; set; }
        public string sistema { get; set; }
        public string proceso { get; set; }
        public int? nvnumero { get; set; }
        public string contabpago { get; set; }
        public int? numguiatrasp { get; set; }
        public int? fueexportado { get; set; }
        public string id_paquete { get; set; }
        public string nrovale { get; set; }
        public string cancod { get; set; }
        public int? esdevolucion { get; set; }
        public string cwcpbano { get; set; }
        public string cwcpbnum { get; set; }
        public string marcawg { get; set; }
        public string cpbanodespp { get; set; }
        public string cpbnumdespp { get; set; }
        public string cpbanopagos { get; set; }
        public string cpbnumpagos { get; set; }
        public string cod_distrib { get; set; }
        public string nom_distrib { get; set; }
        public DateTime? fechoracreacion { get; set; }
        public int? listamayorista { get; set; }
        public int? boletafiscal { get; set; }
        public int? impresaok { get; set; }
        public int? cpbanoventas { get; set; }
        public int? cpbnumventas { get; set; }
        public string cpbanocostos { get; set; }
        public int? cpbnumcostos { get; set; }
        public string cpbanoconsumos { get; set; }
        public string cpbnumconsumos { get; set; }
        public int? contabenpw { get; set; }
        public string ttdcod { get; set; }
        public string rutsolicitante { get; set; }
        public string ruttransportista { get; set; }
        public string tipdocref { get; set; }
        public string subtipdocref { get; set; }
        public int? desclispreenmov { get; set; }
        public int? motivoncnd { get; set; }
        public int? correlativoaprobacion { get; set; }
        public string cpbanocompras { get; set; }
        public string cpbnumcompras { get; set; }
        public int? dte_siitdoc { get; set; }
        public int? contabencw { get; set; }
        public int? factorcostoimportacion { get; set; }
        public string codconvenio { get; set; }
        public string fechaemisconv { get; set; }
        public int? tipodespacho { get; set; }
        public int? totaldescboleta { get; set; }
        public string cpbanocostosifrs { get; set; }
        public string cpbnumcostosifrs { get; set; }
        public string cpbanoconsumosifrs { get; set; }
        public string cpbnumconsumosifrs { get; set; }
        public string cpbanocomprasifrs { get; set; }
        public string cpbnumcomprasifrs { get; set; }
        public string dondedice { get; set; }
        public string debedecir { get; set; }
        public string otrorut { get; set; }
        public int? tiposerviciosii { get; set; }
        public string cpbanotomainv { get; set; }
        public string cpbnumtomainv { get; set; }
        public DateTime? fechoracreacionvw { get; set; }
        public int? nrointdctorefaut { get; set; }
        public string tipodctorefaut { get; set; }
        public int? porccredempconst { get; set; }
        public int? desccredempconst { get; set; }
        public double? netoafectolf { get; set; }
        public double? netoexentolf { get; set; }
        public double? ivalf { get; set; }
        public double? totallf { get; set; }
        public DateTime? fechainilf { get; set; }
        public DateTime? fechafinlf { get; set; }
        public string pagocontarjeta { get; set; }
        public string idlectortarjeta { get; set; }
        public string nropicking { get; set; }
        public string comprobantepago { get; set; }
        public string codlugardocto { get; set; }
        public int? tipotrans { get; set; }
        public string fmapago { get; set; }
        public string nroembarque { get; set; }
        public int? esimportacion { get; set; }
        public string codauxmandante { get; set; }
        public string nomcontacto { get; set; }
        public DateTime? fechagendte { get; set; }
        public string gircod { get; set; }
        public string girdes { get; set; }
        public string ciudes { get; set; }
        public string ciucod { get; set; }
        public string comcod { get; set; }
        public string comdes { get; set; }
        public string fonaux1 { get; set; }
        public string vendes { get; set; }
        public string desmon { get; set; }
        public string desdir { get; set; }
        public string descomdch { get; set; }
        public string desciudch { get; set; }
        public string despaidch { get; set; }
        public string deslistaprecio { get; set; }
        public DateTime fechahoracreacion { get; set; }
        public string subtipo { get; set; }
    }

    public class Detalle
    {
        public string Tipo { get; set; }
        public int? Nroint { get; set; }
        public int? Linea { get; set; }
        public string CodProd { get; set; }
        public string CodBode { get; set; }
        public DateTime? Fecha { get; set; }
        public int? CantIngresada { get; set; }
        public int? CantDespachada { get; set; }
        public int? CantFacturada { get; set; }
        public decimal? PreUniMB { get; set; }
        public int? PreUniMVta { get; set; }
        public int? PreUniMOrig { get; set; }
        public DateTime? FechaCompra { get; set; }
        public double? PorcDescMov01 { get; set; }
        public int? DescMov01 { get; set; }
        public double? PorcDescMov02 { get; set; }
        public int? DescMov02 { get; set; }
        public double? PorcDescMov03 { get; set; }
        public int? DescMov03 { get; set; }
        public double? PorcDescMov04 { get; set; }
        public int? DescMov04 { get; set; }
        public double? PorcDescMov05 { get; set; }
        public int? DescMov05 { get; set; }
        public double? TotalDescMov { get; set; }
        public decimal? Equivalencia { get; set; }
        public int? Actualizado { get; set; }
        public decimal? TotLinea { get; set; }
        public string DetProd { get; set; }
        public int? nvCorrela { get; set; }
        public string Partida { get; set; }
        public string Pieza { get; set; }
        public DateTime? FechaVencto { get; set; }
        public string Ubicacion { get; set; }
        public string TipoOrigen { get; set; }
        public string TipoDestino { get; set; }
        public string AuxTipo { get; set; }
        public int? CodAux { get; set; }
        public string CodiCC { get; set; }
        public int? Orden { get; set; }
        public int? ocCorrela { get; set; }
        public string KIT { get; set; }
        public int? MarcaWG { get; set; }
        public int? ImpresaOk { get; set; }
        public string CuentaConsumo { get; set; }
        public string CodPromocion { get; set; }
        public string CodUMed { get; set; }
        public int? CantFactUVta { get; set; }
        public int? CantDespUVta { get; set; }
        public int? NumTrab { get; set; }
        public string CodProOF { get; set; }
        public int? Recargo { get; set; }
        public int? TotalDescMovBoleta { get; set; }
        public int? PreUniBoleta { get; set; }
        public int? TotalBoleta { get; set; }
        public string SolicitudMT { get; set; }
        public string NroLineaMT { get; set; }
        public int? PorcRecMov01 { get; set; }
        public int? RecMov01 { get; set; }
        public int? NVCorrelaOC { get; set; }
        public int? NroLintran { get; set; }
        public string Refinterna { get; set; }
        public string DesUMed { get; set; }
    }

    public class Dte
    {
        public string firmadte { get; set; }
        public string archivo { get; set; }
        public int? tipo { get; set; }
        public int? id_archivo { get; set; }
        public string nombre_archivo { get; set; }
    }

    public class Referencia
    {
        public string DesRefSII { get; set; }
        public int? FolioRef { get; set; }
        public string CodRefSii { get; set; }
        public DateTime FechaRef { get; set; }
    }

    public class DocumentoAPIDTO
    {
        public Cabecera cabecera { get; set; }
        public List<Detalle> detalle { get; set; }
        public List<Referencia> referencias { get; set; }
        public Dte dte { get; set; }
    }
}
